---
name: Manage GitHub Repository

on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: 'Repository name'
        required: true
        type: string
      repo-description:
        description: 'Repository description'
        required: false
        default: 'This repository was provisioned with Terraform without a description.'
        type: string
      auto-init:
        description: 'Auto initialize repository with README and main branch'
        required: false
        default: true
        type: boolean
      additional-branches:
        description: 'Optional branches list (e.g., ''["dev","docs"]'')'
        required: false
        default: ''
        type: string
      github-owner:
        description: 'GitHub organization or user'
        required: false
        default: 'redjax'
        type: string
      visibility:
        description: 'Public or private visibility'
        required: false
        default: 'private'
        type: choice
        options:
          - private
          - public
      destroy:
        description: 'Perform destroy instead of deploy'
        required: false
        default: false
        type: boolean

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: github_repo_plan

    steps:
      - uses: actions/checkout@v5

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: latest
          tofu_wrapper: false

      - name: Set up Terragrunt
        uses: gruntwork-io/terragrunt-action@v3
        with:
          tg_version: latest

      - name: Set Terraform environment variables
        run: |
          echo "TF_VAR_repository_name=\"${{ github.event.inputs.repo-name }}\"" >> $GITHUB_ENV
          echo "TF_VAR_repository_description=\"${{ github.event.inputs.repo-description }}\"" >> $GITHUB_ENV
          echo "TF_VAR_repository_auto_init=${{ github.event.inputs.auto-init }}" >> $GITHUB_ENV
          echo "TF_VAR_additional_branches='${{ github.event.inputs.additional-branches }}'" >> $GITHUB_ENV
          echo "TF_VAR_github_owner=${{ github.event.inputs.github-owner }}" >> $GITHUB_ENV
          echo "TF_VAR_github_token=${{ secrets.GH_PAT }}" >> $GITHUB_ENV
          echo "TF_VAR_visibility=${{ github.event.inputs.visibility }}" >> $GITHUB_ENV

      - name: Configure AWS credentials for Backblaze B2
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.B2_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.B2_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set checksum environment variables
        run: |
          echo "AWS_REQUEST_CHECKSUM_CALCULATION=when_required" >> $GITHUB_ENV
          echo "AWS_RESPONSE_CHECKSUM_VALIDATION=when_required" >> $GITHUB_ENV

      - name: Terragrunt plan (apply or destroy)
        working-directory: ./environments/github/repos/BasicRepository
        run: |
          if [ "${{ github.event.inputs.destroy }}" == "true" ]; then
            echo "Running destroy plan"
            terragrunt plan -destroy
          else
            echo "Running standard plan"
            terragrunt plan
          fi

  apply:
    runs-on: ubuntu-latest
    needs: plan
    environment:
      name: github_repo_deployment

    steps:
      - uses: actions/checkout@v5

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: latest
          tofu_wrapper: false

      - name: Set up Terragrunt
        uses: gruntwork-io/terragrunt-action@v3
        with:
          tg_version: latest

      - name: Set Terraform environment variables
        run: |
          echo "TF_VAR_repository_name=\"${{ github.event.inputs.repo-name }}\"" >> $GITHUB_ENV
          echo "TF_VAR_repository_description=\"${{ github.event.inputs.repo-description }}\"" >> $GITHUB_ENV
          echo "TF_VAR_repository_auto_init=${{ github.event.inputs.auto-init }}" >> $GITHUB_ENV
          echo "TF_VAR_additional_branches='${{ github.event.inputs.additional-branches }}'" >> $GITHUB_ENV
          echo "TF_VAR_github_owner=${{ github.event.inputs.github-owner }}" >> $GITHUB_ENV
          echo "TF_VAR_github_token=${{ secrets.GH_PAT }}" >> $GITHUB_ENV
          echo "TF_VAR_visibility=${{ github.event.inputs.visibility }}" >> $GITHUB_ENV

      - name: Configure AWS credentials for Backblaze B2
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.B2_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.B2_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set checksum environment variables
        run: |
          echo "AWS_REQUEST_CHECKSUM_CALCULATION=when_required" >> $GITHUB_ENV
          echo "AWS_RESPONSE_CHECKSUM_VALIDATION=when_required" >> $GITHUB_ENV

      - name: Terragrunt apply or destroy
        working-directory: ./environments/github/repos/BasicRepository
        run: |
          if [ "${{ github.event.inputs.destroy }}" == "true" ]; then
            terragrunt destroy -auto-approve
          else
            terragrunt apply -auto-approve
          fi
