name: Create New Github Repo

on:
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: environments/github/repos/BasicRepository

    steps:
    - uses: actions/checkout@v4

    - name: Set up direnv environment
      run: |
        sudo apt-get update -y
        sudo apt-get install -y direnv
        eval "$(direnv hook bash)"
        direnv allow .

    - name: Terragrunt plan
      uses: gruntwork-io/terragrunt-action@v2
      with:
        tg_version: latest
        tg_dir: environments/github/repos/BasicRepository
        tg_command: plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REQUEST_CHECKSUM_CALCULATION: ${{ secrets.AWS_REQUEST_CHECKSUM_CALCULATION }}
        AWS_RESPONSE_CHECKSUM_VALIDATION: ${{ secrets.AWS_RESPONSE_CHECKSUM_VALIDATION }}

        TF_VAR_repository_name: ${{ secrets.REPOSITORY_NAME }}
        TF_VAR_repository_auto_init: ${{ secrets.REPOSITORY_AUTO_INIT }}
        TF_VAR_additional_branches: ${{ secrets.ADDITIONAL_BRANCHES }}
        TF_VAR_github_owner: ${{ secrets.GITHUB_OWNER }}
        TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload plan artifact
      uses: actions/upload-artifact@v4
      with:
        name: basicrepo-plan
        path: .

  apply:
    runs-on: ubuntu-latest
    needs: plan
    environment:
      name: production

    defaults:
      run:
        working-directory: environments/github/repos/BasicRepository

    steps:
    - uses: actions/checkout@v4

    - name: Set up direnv environment
      run: |
        sudo apt-get update -y
        sudo apt-get install -y direnv
        eval "$(direnv hook bash)"
        direnv allow .

    - name: Terragrunt apply
      uses: gruntwork-io/terragrunt-action@v2
      with:
        tg_version: latest
        tg_dir: environments/github/repos/BasicRepository
        tg_command: apply
        tg_add_approve: 1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REQUEST_CHECKSUM_CALCULATION: ${{ secrets.AWS_REQUEST_CHECKSUM_CALCULATION }}
        AWS_RESPONSE_CHECKSUM_VALIDATION: ${{ secrets.AWS_RESPONSE_CHECKSUM_VALIDATION }}

        TF_VAR_repository_name: ${{ secrets.REPOSITORY_NAME }}
        TF_VAR_repository_auto_init: ${{ secrets.REPOSITORY_AUTO_INIT }}
        TF_VAR_additional_branches: ${{ secrets.ADDITIONAL_BRANCHES }}
        TF_VAR_github_owner: ${{ secrets.GITHUB_OWNER }}
        TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
